### PR TITLE
Edited the layout of the readme file.

### PR DESCRIPTION
**Pull request by Terunaga**
# WHAT

Edited the layout of the readme file.
# WHY

The markdown formatting doesn't seem to be working properly.

### CODE REVIEW

**Comment by sinagaki58** [comment]
thumbnailsのmain,subはそれぞれカラムを設けるのではなく、例えばstatusみたいなカラム1つだけで区別することができます

**Comment by sinagaki58** [comment]
readmeの拡張子は.mdにしましょう

**Comment by Terunaga** [comment]
# WHAT
1. Changed the extension from rdoc to md.
2. Deleted main_thumbnail column and sub_thumbnail colum, and added image column.

# WHY
1. md works better.
2. One column is sufficient to manage several thumbnails.

**Comment by Terunaga** [comment]
# WHAT

Changed the column name from "image" to "status" in the thumbnails table.

# WHY

A column like that of "status" is required in enum.

**Comment by Terunaga** [comment]
# WHAT

Added "name" column to thumbnails table.

# WHY

"name" column will manage the thumbnails.

**Pull request merged**
